/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Button classes
    "btn-primary",
    "btn-secondary",
    "btn-accent",
    "btn-outline",
    // Color classes that might be dynamically used
    "text-[var(--green)]",
    "text-[var(--navy-blue)]",
    "text-[var(--red)]",
    "text-[var(--light-blue)]",
    "text-[var(--grey)]",
    "bg-[var(--green)]",
    "bg-[var(--navy-blue)]",
    "bg-[var(--red)]",
    "bg-[var(--light-blue)]",
    "bg-[var(--grey)]",
    // Focus ring classes
    "focus:ring-green-200",
    "focus:ring-red-200",
    "focus:ring-blue-200",
    "focus:ring-gray-200",
    // Hover states
    "hover:bg-emerald-600",
    "hover:bg-gray-50",
    // Common utility classes
    "flex-shrink-0",
    "mt-1",
    "mt-0.5",
    "mr-1",
    "mr-2",
    "mr-3",
    // Grid classes
    "grid-cols-1",
    "grid-cols-2",
    "md:grid-cols-2",
    // Additional classes for courses page
    "bg-[var(--red-dark)]",
    "border-[var(--navy-blue)]",
    "focus:outline-none",
    "hover:bg-red-700",
    "hover:bg-blue-900",
    "items-start",
    "items-center",
    "justify-center",
    "ml-2",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-6",
    "mb-8",
    "p-3",
    "p-4",
    "p-5",
    "p-6",
    "py-1",
    "py-3",
    "px-3",
    "px-6",
    "px-8",
    "space-y-2",
    "space-y-3",
    "gap-1",
    "gap-2",
    "gap-8",
    "text-sm",
    "text-lg",
    "text-xl",
    "text-3xl",
    "text-gray-600",
    "text-gray-700",
    "text-white",
    "bg-gray-50",
    "bg-white",
    "border-gray-200",
    "w-4",
    "w-5",
    "h-4",
    "h-5",
    "inline-block",
    "rounded-full",
    "inline-flex",
    "font-medium",
    "font-semibold",
    "transition-colors",
    // Other dynamic classes that might be purged
    {
      pattern: /text-(red|green|blue|gray)-(400|500|600|700)/,
    },
    {
      pattern: /bg-(red|green|blue|gray)-(50|100|200|500|600)/,
    },
    // CSS variable patterns - removing problematic regex
    "text-[var(--navy-blue)]",
    "text-[var(--red)]",
    "text-[var(--green)]",
    "text-[var(--light-blue)]",
    "text-[var(--grey)]",
    "bg-[var(--navy-blue)]",
    "bg-[var(--red)]",
    "bg-[var(--green)]",
    "bg-[var(--light-blue)]",
    "bg-[var(--grey)]",
  ],
  theme: {
    extend: {
      colors: {
        "navy-blue": "#003366",
        red: "#e63946",
        green: "#2a9d8f",
        "light-blue": "#4cc9f0",
        grey: "#6c757d",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
